version: '3'

# networks:
#   academe-platform_sociobee_network:
#     external: true
networks:
  my_network:
    driver: bridge

volumes:
  data-volume:

services:

  mysql:
    image: mysql
    build: ./Model
    volumes:
    #- ./Model/init.sql:/docker-entrypoint-initdb.d/dump.sql
    - data-volume:/var/lib/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: SocioBeeMVE
      MYSQL_ROOT_PASSWORD: mypasswd
    ports:
      - "3306:3306"
    networks:
      - my_network
    # networks:
    #   - academe-platform_sociobee_network

  api:
    depends_on:
      - mysql
    container_name: MVE
    platform: linux/x86_64
    build: .
    links:
      - mysql
    restart: always
    tty: true
    volumes:
    - ./:/recommendersystem
    ports:
      - 8001:8001
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=mve
      - DATABASE_PASSWORD=mvepasswd123
      - DATABASE=SocioBeeMVE
      - DATABASE_HOST=mysql
    # networks:
    #   - academe-platform_sociobee_network
    networks:
      - my_network
  mysql_bot:
    image: mysql_bot
    build: ./Telegram_bot/Model
    volumes:
    #- ./Model/init.sql:/docker-entrypoint-initdb.d/dump.sql
    - data-volume:/var/lib/mysql_bot
    container_name: mysql_bot
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: Telegram_bot_db
      MYSQL_ROOT_PASSWORD: mypasswd
    ports:
      - "3307:3306"
    networks:
      - my_network
    # networks:
    #   - academe-platform_sociobee_network

  telegram_bot:
    depends_on:
      - mysql_bot
    container_name: telegram_bot
    platform: linux/x86_64
    build: ./Telegram_bot
    links:
      - mysql_bot
    restart: always
    tty: true
    volumes:
    - ./:/telegram_bot
    ports:
      - 8002:8001
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=telegram_bot
      - DATABASE_PASSWORD=telegram_botpasswd123
      - DATABASE=Telegram_bot_db
      - DATABASE_HOST=mysql_bot
    # networks:
    #   - academe-platform_sociobee_network
    networks:
      - my_network